name: chia_crypto_utils
description: Utilities for the Chia blockchain.
version: 1.0.0

environment:
    sdk: '>=2.14.3 <3.0.0'

dev_dependencies:
    lints: ^1.0.0
    test: ^1.19.3

dependencies:
    hex: ^0.2.0
    quiver: ^3.0.1+1
