name: chia_utils
description: Utilities for the Chia blockchain.
version: 1.0.13

environment:
  sdk: '>=2.15.0 <3.0.0'

scripts:
  integration_tests: 'dart test integration_test/ --concurrency=1'

dependencies:
  bech32m: ^0.2.2
  bip39: ^1.0.6
  get_it: ^7.2.0
  hex: ^0.2.0
  injector: ^2.0.0
  meta: ^1.7.0
  quiver: ^3.0.1+1
  yaml: ^3.1.1

dev_dependencies:
  csv: ^5.0.1
  http: ^0.13.4
  lints: ^1.0.0
  rps: ^0.6.3
  test: ^1.19.3
  very_good_analysis: ^2.4.0
